In [24]:
import pandas as pd

In [25]:
deaths = pd.read_csv('US_Vital_Stats_Deaths.csv')

In [26]:
population = pd.read_csv('pop_merge.csv')

In [27]:
population.columns

Index(['STNAME', 'CTYNAME', 'Year', 'Population'], dtype='object')

In [28]:
population.head(10)

    STNAME          CTYNAME  Year  Population
0  Alabama          Alabama  2006     4597688
1  Alabama   Autauga County  2006       49105
2  Alabama   Baldwin County  2006      168516
3  Alabama   Barbour County  2006       29556
4  Alabama      Bibb County  2006       21285
5  Alabama    Blount County  2006       55978
6  Alabama   Bullock County  2006       10739
7  Alabama    Butler County  2006       20231
8  Alabama   Calhoun County  2006      112453
9  Alabama  Chambers County  2006       34822

In [29]:
deaths.head(10)

,County,County Code,Year,Year Code,Drug/Alcohol Induced Cause,Drug/Alcohol Induced Cause Code,Deaths
0,"Autauga County, AL",1001,2009.0,2009.0,All other non-drug and non-alcohol causes,O9,408.0
1,"Baldwin County, AL",1003,2009.0,2009.0,Drug poisonings (overdose) Unintentional (X40-...,D1,29.0
2,"Baldwin County, AL",1003,2009.0,2009.0,All other non-drug and non-alcohol causes,O9,1669.0
3,"Barbour County, AL",1005,2009.0,2009.0,All other non-drug and non-alcohol causes,O9,299.0
4,"Bibb County, AL",1007,2009.0,2009.0,All other non-drug and non-alcohol causes,O9,207.0
5,"Blount County, AL",1009,2009.0,2009.0,All other non-drug and non-alcohol causes,O9,541.0
6,"Bullock County, AL",1011,2009.0,2009.0,All other non-drug and non-alcohol causes,O9,112.0
7,"Butler County, AL",1013,2009.0,2009.0,All other non-drug and non-alcohol causes,O9,242.0
8,"Calhoun County, AL",1015,2009.0,2009.0,Drug poisonings (overdose) Unintentional (X40-...,D1,12.0
9,"Calhoun County, AL",1015,2009.0,2009.0,All other non-drug and non-alcohol causes,O9,1317.0

In [30]:
deaths[['CTYNAME','STNAME']] = deaths['County'].str.split(',', n=1, expand=True)

In [31]:
deaths = deaths[['CTYNAME', 'STNAME','County', 'County Code', 'Year', 'Year Code',
       'Drug/Alcohol Induced Cause', 'Drug/Alcohol Induced Cause Code',
       'Deaths']]

In [32]:
deaths.head(10)

,CTYNAME,STNAME,County,County Code,Year,Year Code,Drug/Alcohol Induced Cause,Drug/Alcohol Induced Cause Code,Deaths
0,Autauga County,AL,"Autauga County, AL",1001,2009.0,2009.0,All other non-drug and non-alcohol causes,O9,408.0
1,Baldwin County,AL,"Baldwin County, AL",1003,2009.0,2009.0,Drug poisonings (overdose) Unintentional (X40-...,D1,29.0
2,Baldwin County,AL,"Baldwin County, AL",1003,2009.0,2009.0,All other non-drug and non-alcohol causes,O9,1669.0
3,Barbour County,AL,"Barbour County, AL",1005,2009.0,2009.0,All other non-drug and non-alcohol causes,O9,299.0
4,Bibb County,AL,"Bibb County, AL",1007,2009.0,2009.0,All other non-drug and non-alcohol causes,O9,207.0
5,Blount County,AL,"Blount County, AL",1009,2009.0,2009.0,All other non-drug and non-alcohol causes,O9,541.0
6,Bullock County,AL,"Bullock County, AL",1011,2009.0,2009.0,All other non-drug and non-alcohol causes,O9,112.0
7,Butler County,AL,"Butler County, AL",1013,2009.0,2009.0,All other non-drug and non-alcohol causes,O9,242.0
8,Calhoun County,AL,"Calhoun County, AL",1015,2009.0,2009.0,Drug poisonings (overdose) Unintentional (X40-...,D1,12.0
9,Calhoun County,AL,"Calhoun County, AL",1015,2009.0,2009.0,All other non-drug and non-alcohol causes,O9,1317.0

In [33]:
deaths['Year'] = deaths['Year'].astype(int)

In [34]:
deaths.dtypes

CTYNAME                             object
STNAME                              object
County                              object
County Code                          int64
Year                                 int64
Year Code                          float64
Drug/Alcohol Induced Cause          object
Drug/Alcohol Induced Cause Code     object
Deaths                              object
dtype: object

In [35]:
stats_abb = pd.read_csv('states_abb.csv')

### Merge state_abb with deaths dataset

In [36]:
deaths.columns

Index(['CTYNAME', 'STNAME', 'County', 'County Code', 'Year', 'Year Code',
       'Drug/Alcohol Induced Cause', 'Drug/Alcohol Induced Cause Code',
       'Deaths'],
      dtype='object')

In [39]:
stats_abb = stats_abb.rename(columns={'Abbreviation': 'STNAME'})

In [58]:
deaths['STNAME'] = deaths['STNAME'].str.strip()

In [60]:
merge_data = pd.merge(deaths,stats_abb,how='left',on='STNAME')

### Merge it with population data

In [62]:
population.head(10)

    STNAME          CTYNAME  Year  Population
0  Alabama          Alabama  2006     4597688
1  Alabama   Autauga County  2006       49105
2  Alabama   Baldwin County  2006      168516
3  Alabama   Barbour County  2006       29556
4  Alabama      Bibb County  2006       21285
5  Alabama    Blount County  2006       55978
6  Alabama   Bullock County  2006       10739
7  Alabama    Butler County  2006       20231
8  Alabama   Calhoun County  2006      112453
9  Alabama  Chambers County  2006       34822

In [63]:
population = population.rename(columns={'STNAME': 'State'})

In [75]:
final_merge = pd.merge(merge_data,population,how='inner',on=['State','CTYNAME','Year'])

In [82]:
final_merge['Deaths'] = final_merge['Deaths'].astype(float).astype(int)

In [83]:
final_merge.dtypes

CTYNAME                             object
STNAME                              object
County                              object
County Code                          int64
Year                                 int64
Year Code                          float64
Drug/Alcohol Induced Cause          object
Drug/Alcohol Induced Cause Code     object
Deaths                               int64
State                               object
Population                           int64
dtype: object

In [84]:
final_merge['Mortality_Rate'] = final_merge['Deaths'] / final_merge['Population']

In [85]:
final_merge.head(10)

,CTYNAME,STNAME,County,County Code,Year,Year Code,Drug/Alcohol Induced Cause,Drug/Alcohol Induced Cause Code,Deaths,State,Population,Mortality_Rate
0,Autauga County,AL,"Autauga County, AL",1001,2009,2009.0,All other non-drug and non-alcohol causes,O9,408,Alabama,50756,0.008038
1,Baldwin County,AL,"Baldwin County, AL",1003,2009,2009.0,Drug poisonings (overdose) Unintentional (X40-...,D1,29,Alabama,179878,0.000161
2,Baldwin County,AL,"Baldwin County, AL",1003,2009,2009.0,All other non-drug and non-alcohol causes,O9,1669,Alabama,179878,0.009279
3,Barbour County,AL,"Barbour County, AL",1005,2009,2009.0,All other non-drug and non-alcohol causes,O9,299,Alabama,29737,0.010055
4,Bibb County,AL,"Bibb County, AL",1007,2009,2009.0,All other non-drug and non-alcohol causes,O9,207,Alabama,21587,0.009589
5,Blount County,AL,"Blount County, AL",1009,2009,2009.0,All other non-drug and non-alcohol causes,O9,541,Alabama,58345,0.009272
6,Bullock County,AL,"Bullock County, AL",1011,2009,2009.0,All other non-drug and non-alcohol causes,O9,112,Alabama,10985,0.010196
7,Butler County,AL,"Butler County, AL",1013,2009,2009.0,All other non-drug and non-alcohol causes,O9,242,Alabama,19964,0.012122
8,Calhoun County,AL,"Calhoun County, AL",1015,2009,2009.0,Drug poisonings (overdose) Unintentional (X40-...,D1,12,Alabama,114081,0.000105
9,Calhoun County,AL,"Calhoun County, AL",1015,2009,2009.0,All other non-drug and non-alcohol causes,O9,1317,Alabama,114081,0.011544